### ISSUE TITLE
Class DigitalInputDevice: Missing factor 1000 in debouncing when recalculating stop time

### ISSUE THREAD

**Issue by SmokeyBrandie** [RaspberryPiFoundation/picozero#101]
In this line https://github.com/RaspberryPiFoundation/picozero/blob/dev/picozero/picozero.py#L1601
the stop time is resetted, when state changes within debouncing time.

`stop = ticks_ms() + self._bounce_time`

From my point of view there is a missing "* 1000", because "self._bounce_time" is in seconds.

This line should be exactliy like the one above: https://github.com/RaspberryPiFoundation/picozero/blob/dev/picozero/picozero.py#L1597

`stop = ticks_ms() + (self._bounce_time * 1000)`

**Comment by martinohanlon** [comment]
Yes, I agree, it just looks like a simple oversight. It would have affected the bounce time when values changed.

I have prepared a fix in PR #104

**Comment by martinohanlon** [comment]
This has been resolved in 0.4.2 

@MarcScott - can you close the issue please.
