### ISSUE TITLE
pot controlled speaker

### ISSUE THREAD

**Issue by MarcScott** [RaspberryPiFoundation/picozero#30]
## Code
```
def speaker_pitch_by_pot():
    from picozero import Pot, Speaker
    pot = Pot(27)
    speaker = Speaker(17)
    while True:
        speaker.play(pot.percent * 10 + 1000)
```

## Expected
A smooth graduation of tones as the pot is turned

## Result
Notes only change after the duration limit is reached, meaning that it has the sound of a digital, rather than analogue dial.

**Comment by martinohanlon** [comment]
Can this be closed?
