### ISSUE TITLE
blink rate of zero causes Traceback error

### ISSUE THREAD

**Issue by MarcScott** [RaspberryPiFoundation/picozero#32]
## Code
```
>>> from picozero import LED
>>> led = LED(15)
>>> led.blink(0)
```

## Error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "picozero.py", line 377, in blink
  File "picozero.py", line 177, in _start_change
  File "picozero.py", line 41, in __init__
  File "picozero.py", line 57, in _set_value
  File "picozero.py", line 82, in _get_value
StopIteration: 
```

Found as I'm trying to use a pot to control blink rates,

**Comment by martinohanlon** [comment]
This bug occurs because the generator never returns a value and an error is raised in the exception handler of `ValueChange._get_value`.

```python
    def _get_value(self):
        try:
            
            return next(self._gen)
            
        except StopIteration:
            
            self._n = self._n - 1 if self._n is not None else None
            if self._n == 0:
                # its the end, return None
                return None
            else:
                # recreate the generator and start again
                self._gen = self._generator()
                return next(self._gen)
```

I will ponder what we might want to do about this.

**Comment by martinohanlon** [comment]
Fixed in dev.

No exception is raised but the LED wont turn on. This makes sense to me because `on_time=0` so its never on. Or more accurately is on but there is no delay between it turning on and then turning off.

**Comment by martinohanlon** [comment]
Fixed again in dev...  I managed to break `pulse`. This is why we create tests!

`blink` now validates that there is actually something to change (e.g. there is a time greater than zero) before starting up the ValueChange. Simpler solution... Should have done it this way in the first place.

**Comment by martinohanlon** [comment]
Release with v0.3.0
