### ISSUE TITLE
Blinking LED controlled by pot

### ISSUE THREAD

**Issue by MarcScott** [RaspberryPiFoundation/picozero#33]
## Code

```
def led_blink_rate_by_pot(pot_pin, led_pin):
    from picozero import Pot, LED
    from utime import sleep
    pot = Pot(pot_pin)
    led = LED(led_pin)
    while True:
        led.on()
        sleep(pot.value)
        led.off()
        sleep(pot.value)
```

## Question

Is this the best way of doing this, or am I missing some simpler way of being able to pass the `pot.value` into the `on` `off` times for the `blink` method?

**Comment by martinohanlon** [comment]
@MarcScott can this be closed?

**Comment by martinohanlon** [comment]
@MarcScott can this issue also be closed?

**Comment by MarcScott** [comment]
Yes, close the issue
