### ISSUE TITLE
Potentiometer-pwmled example should be added

### ISSUE THREAD

**Issue by sentairanger** [RaspberryPiFoundation/picozero#78]
Hello, I was trying to find a way to use a potentiometer to change the value of an LED and I was able to get it to work. I created this issue to recommend adding this sample code I created to the official documentation as an example for others to try out. Thank you. Sample code below works as expected.

```python
from picozero import Pot, PWMLED
from time import sleep

pot = Pot(0)
red =  PWMLED(16)

while True:
    print(pot.value, pot.voltage)
    red.on(value=pot.value)
    sleep(0.1)```

**Comment by martinohanlon** [comment]
Thank you for your suggestion. I will add it to the recipes the next time I do a release.

**Comment by sentairanger** [comment]
Thank you Martin I will now close this issue.

**Comment by martinohanlon** [comment]
I have reopened the issue as the change hasn't yet been made.

**Comment by martinohanlon** [comment]
I have added a recipe to the documentation.
