### ISSUE TITLE
not percent attribute

### ISSUE THREAD

**Issue by jrobinson-uk** [RaspberryPiFoundation/picozero#79]
The Pot object has no attribute 'percent'

https://github.com/RaspberryPiFoundation/picozero/blob/762096f615cb08ca5542c24f3e26d7693f261c17/docs/examples/potentiometer.py#L9

**Comment by martinohanlon** [comment]
Thank you :)

This has been fixed in `dev`

**Comment by martinohanlon** [comment]
released
