### ISSUE TITLE
ADC0 not clear

### ISSUE THREAD

**Issue by jrobinson-uk** [RaspberryPiFoundation/picozero#80]
'ADC0' doesn't match any pin label printed on pico (perhaps add 'GP26')

https://github.com/RaspberryPiFoundation/picozero/blob/762096f615cb08ca5542c24f3e26d7693f261c17/docs/examples/potentiometer.py#L9

**Comment by martinohanlon** [comment]
Thank you.

I have changed to

```
# Potentiometer connected to GP26 (ADC0), GND and 3V

from time import sleep
from pico import Pot

pot = Pot(26)

while True:
    print(pot.value, pot.voltage)
    sleep(0.1)
```

It is in dev

**Comment by martinohanlon** [comment]
released
